name: Lint

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    eslint:
        name: eslint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: install node v12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: yarn install
              run: yarn install
            - name: eslint
              uses: icrawl/action-eslint@v1
